### ISSUE TITLE
possible EventEmitter memory leak on MQTT reconnecting

### ISSUE THREAD

**Issue by kosich** [garage-it/SmartHouse-backend#44]
(node) warning: possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at MqttClient.addListener (events.js:252:17)
    at onSubscribed (/Users/kos/projects/epam-smart-house/SmartHouse-backend/dist/src/mqtt-client/client.js:81:12)
    at /Users/kos/projects/epam-smart-house/SmartHouse-backend/node_modules/mqtt/lib/client.js:845:9
    at Store.del (/Users/kos/projects/epam-smart-house/SmartHouse-backend/node_modules/mqtt/lib/store.js:76:5)
    at MqttClient._handleAck (/Users/kos/projects/epam-smart-house/SmartHouse-backend/node_modules/mqtt/lib/client.js:831:26)
    at MqttClient._handlePacket (/Users/kos/projects/epam-smart-house/SmartHouse-backend/node_modules/mqtt/lib/client.js:284:12)
    at process (/Users/kos/projects/epam-smart-house/SmartHouse-backend/node_modules/mqtt/lib/client.js:233:12)
    at Writable.writable._write (/Users/kos/projects/epam-smart-house/SmartHouse-backend/node_modules/mqtt/lib/client.js:243:5)
    at doWrite (/Users/kos/projects/epam-smart-house/SmartHouse-backend/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/kos/projects/epam-smart-house/SmartHouse-backend/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/Users/kos/projects/epam-smart-house/SmartHouse-backend/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Socket.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)

**Comment by stremann** [comment]
@kosich fixed with https://github.com/garage-it/SmartHouse-backend/commit/656ec43f87454b8a23405d060cb81ce1043aedd3
